### ISSUE TITLE
Changes in rights crash the access

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/freshrss_ynh#79]
I tried to change the access rights to freshrss (so only my user have access to it on my instance)
When doing this, I have this warning message
`WARNING - FreshRSS error: username already taken “mamie”`

And then, when trying to access freshrss, I only have a white page saying `### Fatal error! ###`

I solved this by changing the owner of `/var/www/freshrss/data/users/mamie/log.txt` to freshrss:freshrss instead of root:root and I can have access again.

Here is the nginx error I found : 
```
2019/08/26 11:39:33 [error] 24076#24076: *23584 FastCGI sent in stderr: "PHP message: PHP Warning:  file_put_contents(/var/www/freshrss/data/users/mamie/log.txt): failed to open stream: Permission denied in /var/www/freshrss/lib/Minz/Log.php on line 76
PHP message: PHP Warning:  file_put_contents(/var/www/freshrss/data/users/mamie/log.txt): failed to open stream: Permission denied in /var/www/freshrss/lib/Minz/Log.php on line 76
PHP message: PHP Fatal error:  Uncaught Minz_PermissionDeniedException: Permission is denied for `/var/www/freshrss/data/users/mamie/log.txt` in /var/www/freshrss/lib/Minz/Log.php:77
Stack trace:
#0 /var/www/freshrss/lib/Minz/Log.php(141): Minz_Log::record('Permission is d...', 2, '/var/www/freshr...')
#1 /var/www/freshrss/p/i/index.php(51): Minz_Log::error('Permission is d...')
#2 {main}
  thrown in /var/www/freshrss/lib/Minz/Log.php on line 77" while reading response header from upstream, client: **.**.**.**, server: freshrss.myserver.fr, request: "GET /i/?a=normal&get=c_3 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm-freshrss.sock:", host: "freshrss.myserver.fr"
2019/08/26 11:40:23 [error] 24076#24076: *26824 FastCGI sent in stderr: "PHP message: PHP Warning:  file_put_contents(/var/www/freshrss/data/users/mamie/log.txt): failed to open stream: Permission denied in /var/www/freshrss/lib/Minz/Log.php on line 76" while reading response header from upstream, client: **.**.**.**, server: freshrss.myserver.fr, request: "POST /api/pshb.php?k=9715d2acaa53ab97f6fd98897363f4c7b8197879 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm-freshrss.sock:", host: "freshrss.myserver.fr"```

**Comment by supermamie** [comment]
In order to provide credentials for #68 I had to give access to a new user, and I had this fatal error again.

To solve it :
`sudo chown -R freshrss:freshrss /var/www/freshrss/data/users/*`
And it worked again.
